#!/bin/bash

# Invoke the Forever module (to START our Node.js server).
/home/ubuntu/live-analytics/node_modules/forever/bin/forever \
start \
-al forever.log \
-ao out.log \
-ae err.log \
/home/ubuntu/live-analytics/bin/www
